version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: circleci/node:8.15
      - image: mysql:5.6
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
      - MYSQL_DATABASE: circle_test
      - MYSQL_ROOT_PASSWORD: password
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Pruning Dependencies
          command: npm prune
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Compiling Code
          command: npm run build
      - run:
          name: Testing Code
          command: npm run test
      - run:
          name: Linting Code
          command: npm run lint
      - deploy:
          name: Semantic Release
          command: npm run semantic-release
